BlessTheWeb.MVC5/Models/IndulgenceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlessTheWeb.MVC5.Models
{
    public class IndulgenceViewModel
    {
        public string Id { get; set; }
        public string Confession { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
        public string AmountDonated { get; set; }
        public string CharityName { get; set; }
        public string ThumbnailUrl { get; internal set; }
        public Guid Guid { get; internal set; }
    }
}

BlessTheWeb.MVC5/Models/IndulgencesViewModel.cs
using BlessTheWeb.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlessTheWeb.MVC5.Models
{
    public class IndulgencesViewModel
    {
        public Indulgence Indulgence { get; set; }
        public Sin Sin { get; set; }
        public decimal TotalDonated { get; set; }
        public int TotalDonationCount { get; set; }
        public string ImageAlt { get; set; }
    }
}

BlessTheWeb.MVC5/Controllers/IndulgenceController.cs
using BlessTheWeb.Core;
using BlessTheWeb.Core.Repository;
using BlessTheWeb.MVC5.Models;
using log4net;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace BlessTheWeb.MVC5.Controllers
{
    public class IndulgenceController : BlessTheWebController
    {
        private readonly IIndulgeMeService _indulgeMeService;
        private readonly IIndulgenceEmailer _indulgenceEmailer;
        private readonly ILog _log;
        const int pageSize = 12;
        private string contentPath = HostingEnvironment.MapPath("~/content");

        public IndulgenceController(IIndulgeMeService indulgeMeService, IIndulgenceEmailer indulgenceEmailer, ILog log)
        {
            _indulgeMeService = indulgeMeService;
            _indulgenceEmailer = indulgenceEmailer;
            _log = log;
        }

        //
        // GET: /Indulgence/
        public ActionResult Index(string guid)
        {
            if (TempData["absolved"] != null || !string.IsNullOrWhiteSpace(Request.QueryString["congratulations"]))
            {
                ViewData["ShowBlessing"] = true;
            }

            var absolutionViewModel = new IndulgencesViewModel();
            absolutionViewModel.Indulgence = _indulgeMeService.GetIndulgenceByGuid(guid);
            if (absolutionViewModel.Indulgence == null)
                return HttpNotFound("Couldn't find that indulgence");

            if (absolutionViewModel.Indulgence.Sin == null)
                return HttpNotFound("Couldn't find that sin");

            absolutionViewModel.Sin = absolutionViewModel.Indulgence.Sin;
            absolutionViewModel.Sin.Indulgences = _indulgeMeService.AllIndulgencesForSin(absolutionViewModel.Indulgence.Sin).ToList();

            absolutionViewModel.TotalDonationCount = absolutionViewModel.Sin.Indulgences.Count();
            absolutionViewModel.TotalDonated = absolutionViewModel.Sin.Indulgences.Sum(a => a.AmountDonated);
            absolutionViewModel.ImageAlt =
                string.Format("{0} {1} donated {2:c} to {3} on the {4} of {5:MMMM}, {5:yyyy}",
                absolutionViewModel.Indulgence.Confession,
                absolutionViewModel.Indulgence.Name,
                absolutionViewModel.Indulgence.AmountDonated,
                absolutionViewModel.Indulgence.CharityName,
                absolutionViewModel.Indulgence.DateConfessed,
                TextUtils.DayOfMonth(absolutionViewModel.Indulgence.DateConfessed),
                absolutionViewModel.Indulgence);

            return View(absolutionViewModel);
        }

        public ActionResult Email(string guid)
        {
            var indulgence = _indulgeMeService.GetIndulgenceByGuid(guid);

            try
            {
                _indulgenceEmailer.Send(indulgence, string.Format("{0}/indulgence/pdf/{1}",
                    ConfigurationManager.AppSettings["WebsiteHostName"], indulgence.Guid));
            }
            catch (Exception ex)
            {
                _log.Error("Failed to send email", ex);
                throw;
            }

            return new ContentResult()
            {
                Content = "sent",
                ContentType = "text/plain",
                ContentEncoding = Encoding.UTF8
            };
        }

        public ActionResult GenerateImage(string guid)
        {
            var indulgence = _indulgeMeService.GetIndulgenceByGuid(guid);
            if (indulgence == null)
            {
                return new HttpNotFoundResult();
            }

            string fileName = string.Format("{0}/indulgence.pdf", indulgence.Guid);
            string thumbnailFileName = string.Format("{0}/indulgence.png", indulgence.Guid);
            _indulgeMeService.GenerateIndulgence(indulgence, contentPath, contentPath);

            return new ContentResult() { Content = "ok", ContentType = "text/html" };
        }

        public ActionResult Image(string guid, int size)
        {
            var indulgence = _indulgeMeService.GetIndulgenceByGuid(guid);
            if (indulgence == null)
                return HttpNotFound();
            return new FileContentResult(_indulgeMeService.GetIndulgenceImage(indulgence, size), "img/png");
        }

        public ActionResult Pdf(string guid)
        {
            var indulgence = _indulgeMeService.GetIndulgenceByGuid(guid);
            if (indulgence == null)
                return HttpNotFound();
            return new FileContentResult(_indulgeMeService.GetIndulgencePdf(indulgence), "application/pdf");
        }

        public ActionResult GenerateAll()
        {
            StringBuilder sb = new StringBuilder();
            var indulgences = _indulgeMeService.AllIndulgences(0, 9999);

            foreach (var indulgence in indulgences)
            {
                _indulgeMeService.GenerateIndulgence(indulgence, contentPath, contentPath);
                sb.AppendFormat("<p>{0}</p>", indulgence.Guid);
            }

            return new ContentResult() { Content = sb.ToString(), ContentType = "text/html" };
        }

        public ActionResult List(int? page)
        {

            page = page.HasValue ? page.Value : 1;
            var viewModel = new AbsolutionsViewModel();
            int totalIndulgences = _indulgeMeService.IndulgencesCount();
            viewModel.Indulgences = _indulgeMeService.AllIndulgences(page.Value - 1, pageSize);
            viewModel.SiteInfo = _indulgeMeService.GetSiteSummaryInfo();
            viewModel.Page = page.Value;
            viewModel.NextPage = page.Value + 1;
            viewModel.PreviousPage = page.Value > 1 ? page.Value - 1 : 0;
            viewModel.CurrentPage = page.Value;
            viewModel.ShowNextPageLink = (totalIndulgences / pageSize) + 1 > page.Value;
            viewModel.ShowPreviousPageLink = page.Value > 1;

            viewModel.PagingStart = viewModel.CurrentPage - 5 > 1 ? viewModel.CurrentPage - 5 : 1;
            viewModel.PagingEnd = viewModel.CurrentPage + 5 < (totalIndulgences / pageSize) + 1 ? viewModel.CurrentPage + 5 : (totalIndulgences / pageSize) + 1;

            return View(viewModel);
        }
    }
}

BlessTheWeb.MVC5/Views/Indulgence/Index.cshtml
@model BlessTheWeb.MVC5.Models.IndulgencesViewModel

@{
    ViewBag.Title = Model.Indulgence.Confession + " - A Plenary Indulgence";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts {
    <script type="text/javascript" src="/Scripts/indulgence.js"></script>
}
<div id="indulgence-view">
    @if (ViewData["ShowBlessing"] != null && (bool)ViewData["ShowBlessing"] == true)
    {
        <div id="blessing">
            <h2 class="congratulations">Congratulations! Consider yourself blessed.</h2>
            <div id="god_blessing"></div>
        </div>
    }
    @Html.RouteLink("Download a PDF version", "ViewIndulgencePdf", new {guid=Model.Indulgence.Guid})
    <div class="aa">
        <div class="indulgence">
            <img id="indulgence-image" src="/indulgence/image/@Model.Indulgence.Guid/1" alt="@Html.Raw(Model.ImageAlt)" />
        </div>
        @{ Html.RenderPartial("ShareThis", new BlessTheWeb.MVC5.Models.ShareViewModel { Tweet = Model.Indulgence.Confession }); }


        <div style="clear:both" />
        <p><a href="/indulgences/list">View more indulgences</a></p>
        <p><a href="/">God hates your sin. Confess again!</a></p>
    </div>
</div>

BlessTheWeb.MVC5/Views/Indulgence/List.cshtml
@model BlessTheWeb.MVC5.Models.AbsolutionsViewModel

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="indulgence-wall">
    <h2>All Indulgences</h2>
    <div class="container-fluid">
        <div class="row">
            @foreach (var indulgence in Model.Indulgences)
            {
                <div class="indulgence col-xs-12 col-sm-6 col-md-4">
                    <a href="/indulgence/@indulgence.Guid"><img src="/indulgence/image/@indulgence.Guid/3" /></a>
                    <p>
                        <a href="/indulgence/@indulgence.Guid">@(string.IsNullOrWhiteSpace(indulgence.Name) ? "Anonymous" : indulgence.Name), @indulgence.DateConfessed.ToString("hh:mm dd/MM/yyyy")</a>
                    </p>
                </div>
            }
        </div>
    </div>
    <div class="clearfix"></div>
    @if (Model.ShowPreviousPageLink) {
        @Html.ActionLink("Previous Page", "List", "Indulgence", new {page=Model.PreviousPage}, null) 
    }
    @for(int i=Model.PagingStart;i<Model.PagingEnd;i++) {
    <span>@i</span>
    }
    @if (Model.ShowNextPageLink) {
        @Html.ActionLink("Next Page", "List", "Indulgence", new {page=Model.NextPage}, null) 
    }

</div>

BlessTheWeb.MVC5/Views/Indulgence/ShareThis.cshtml
@model BlessTheWeb.MVC5.Models.ShareViewModel

<div id="scripts"></div>
<script type="text/javascript">
    (function () {
        var s = document.createElement('SCRIPT'), s1 = document.getElementById('scripts');
        s.type = 'text/javascript';
        s.async = true;
        s.src = 'http://widgets.digg.com/buttons.js';
        s1.parentNode.insertBefore(s, s1);

        s = document.createElement('SCRIPT')
        s.type = 'text/javascript';
        s.async = true;
        s.src = 'http://connect.facebook.net/en_US/all.js#xfbml=1';
        s1.parentNode.insertBefore(s, s1);

        s = document.createElement('SCRIPT')
        s.type = 'text/javascript';
        s.async = true;
        s.src = 'http://platform.twitter.com/widgets.js';
        s1.parentNode.insertBefore(s, s1);

    })();
</script>

<fb:like show_faces="true" width="450"></fb:like>

<a href="http://twitter.com/share" class="twitter-share-button" data-text="@Html.Raw(Model.Tweet) #blesstheweb" data-count="horizontal" data-via="blesstheweb">Tweet</a>

<a href="http://www.reddit.com/submit" onclick="window.location = 'http://www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false"> <img src="http://www.reddit.com/static/spreddit7.gif" alt="submit to reddit" border="0" /> </a>

<!-- Compact Button -->
<a class="DiggThisButton DiggCompact"></a>